### ISSUE TITLE
pinguino_tools.py/set_os_variables() still useful ?

### ISSUE THREAD

**Issue by rblanchot** [PinguinoIDE/pinguino-ide#30]
pinguino_tools.py/set_os_variables()
    #----------------------------------------------------------------------
    def set_os_variables(self):
        if os.getenv("PINGUINO_OS_NAME") == "windows":
            self.COMPILER_8BIT = os.path.join(self.P8_BIN, "sdcc.exe")
            self.MAKE = os.path.join(self.P32_BIN, "make.exe")
        ...

self.COMPILER_8BIT is redundant with : 

    methods.py/set_board()
    #----------------------------------------------------------------------
            compiler_path = os.path.join(self.configIDE.get_path("sdcc_bin"), "sdcc" + ext)
            libraries_path = self.configIDE.get_path("pinguino_8_libs")

we could just add : 
            make_path = os.path.join(self.configIDE.get_path("sdcc_bin"), "make" + ext)

Note that pinguino_tools.py/compile() and link() functions would have to be modified too.

**Comment by YeisonEng** [comment]
The main reason for this redundant (and others) is because **pinguino_api** is independent from everything else, is the communication between compilers libraries and boards. The IDE (Qt, TkInter, Django) is just an extra layer that uses it.

So pinguino_tools.py/set_os_variables() is used for the compilers,
and methods.py/set_board() is used for the Qt IDE for show information messages if libraries or compilers are missing.

So, yes, they are still useful.

**Comment by rblanchot** [comment]
Ok. Thank you.
