### ISSUE TITLE
No identation leads to error

### ISSUE THREAD

**Issue by rblanchot** [PinguinoIDE/pinguino-ide#34]
void setup()
{
pinMode(USERLED,OUTPUT);
digitalWrite(USERLED,LOW);
}

>>> ERROR: 3:  too many parameters 
>>> 4:  too many parameters 

but this one with identation works : 

void setup()
{
    pinMode(USERLED,OUTPUT);
    digitalWrite(USERLED,LOW);
}

**Comment by YeisonEng** [comment]
This is a bug with preprocessor, fixed in the [commit 5945191001](https://github.com/PinguinoIDE/pinguino-ide/commit/59451910015f85f1202c4e68c662248aee587655).
**Issues related**: https://github.com/PinguinoIDE/pinguino-ide/issues/33 https://github.com/PinguinoIDE/pinguino-ide/issues/34 https://github.com/PinguinoIDE/pinguino-ide/issues/35
