### ISSUE TITLE
Missing Compiler for 8-bit

### ISSUE THREAD

**Issue by jeromejohn77** [PinguinoIDE/pinguino-ide#88]
I have been trying to download the pinguino ide for about a week now and have to ask for help. It seems that no matter what I do I can not get it working properly. I am using windows xp and have searched and tried many sugestions from the internet, all have failed. When I go to compile to my pic18f2550 board I get the message-

[DEBUG] Missing compiler for 8-bit
[DEBUG] Not found: c:\pinguino\compilers\p8 in\sdcc.exe

Please help, I really want to get this board I have going.

Thank you,
Jerome

**Comment by skygunner** [comment]
Yes it is broken in v11, have you tried the v12testing version?

**Comment by skygunner** [comment]
Here's the fix for the Pinguino IDE V11 p8 compiler not found issue:
The IDE is expacting the sdcc compiler to be in 
C:\Pinguino\compilers\p8
and this seems to have been hard coded into it, can it not be changed via paths.cfg file.
The installation have put the sdcc compiler in 
C:\Pinguino\p8 
if you have ticked the option to install p8 compiler during the installation. 

What you need to do to fix this is
just create a new folder named compilers in C:\Pinguino
and move the p8 foldier into it. 

Restart the IDE then it should be happy.

**Comment by Razecus** [comment]
Hi guys,
it os not broken, in the config, file  "C:\Pinguino\v11\user\pinguino.conf" correct the path to match your install, like : " 
[Paths]
sdcc_bin = C:\pinguino\p8\bin\  
gcc_bin = C:\pinguino\p32\bin\
pinguino_8_libs = C:\Pinguino\v11\p8\
pinguino_32_libs = C:\Pinguino\v11\p32\
"
and it will work like it shall do.
